### PR TITLE
HOCS-2778: Comp Creation tests

### PR DESCRIPTION
**Pull request by ARobinson26**
Add tests for `COMP_CREATION.bpmn`

### CODE REVIEW

**Comment by MarkWrightBjss** [comment]
Should the screen contents be covered by HOCS-2778 ?

**Review by philbarton — APPROVED** [review]
Your coverage is actually 0.88888888 :) 
What I do is set it to 99 and then let it fail, but use the new number as the threshold.
Not sure if you were aware but the coverage is also visualised here .....  open target/process-test-coverage/uk.gov.digital.ho.hocs.workflow.processes.COMP_CREATION/COMP_CREATION.html

**Comment by philbarton** [comment]
> Should the screen contents be covered by HOCS-2778 ?

Good point. Not sure.

**Comment by ARobinson26** [comment]
Thanks @philbarton - I'll take a look at the visual, didn't know about that!

Going to look at screen content tests as suggested by @MarkWrightBjss, now.

**Pull request merged**
