### PR TITLE
HOCS-3066 : CCT to Minor team, fix

### PR DESCRIPTION
**Pull request by robertdeniszczyc2**

### CODE REVIEW

**Comment by robertdeniszczyc2** [comment]
PR raised on behalf of @MarkWrightBjss (tech issues meant couldn't raise PR)

**Comment by MarkWrightBjss** [comment]
I tried to raise the PR but angry, pink unicorns kept stopping me!

**Review by robertdeniszczyc2 — COMMENTED** [review]
Looks good to me but I can't approve it because I raised it on behalf of Mark so can't Approve my own PR

**Review by MarkWrightBjss — APPROVED** [review]
This is the best PR I've ever seen, and it's an honour to give it my full approval.

**Pull request merged**
