### PR TITLE
HOCS-2019 : correct bpmn calls to bpmn service to create case note

### PR DESCRIPTION
**Pull request by abarker66**
Corrections made to the calls made from bpmn diagrams to the bpmn Service method to create case notes.
The call to createCaseNote from bpmn diagrams had the wrong parameters, now fixed.

### CODE REVIEW

**Review by MarkWrightBjss — CHANGES_REQUESTED** [review]
1. Please add a unit test for the new "createCaseNote" endpoint.
2. Please add new caste note type to the frontend project.

**Comment by abarker66** [comment]
The BpmnServiceTest mocks the caseworkClient so does not actually add stuff to the database so I don't see the point unless we change the philosophy of testing anything that adds stuff to the databases.I can add one but it will be as useless as the other tests in this class. All they really do is parameter type checking, but it is so mocked it does very little else.

**Comment by abarker66** [comment]
This is blocked for now, the bpmn service tests are mocking all the clients used by bpmn service so are not really performing any functional tests at all. What value do they have??

**Comment by abarker66** [comment]
I cannot mock the calls necessary to add a test for the bpmn.createCaseNote method, they have no return params. The only useful test for this and many other methods in this package would be full on functional checks to the database which would mean quite a bit of work but maybe worth doing for future tests because the existing tests are a nonsense really they are fully mocked and just rigged to pass.

**Comment by abarker66** [comment]
I added a test for createCaseNote to prove that Mockito works. I think it would be well worth investing some time into writing proper functional tests for a focussed regression suite, we have the REST helper so we could call the real methods and read back real results from the database rather than mocking all the clients used by bpmnService and pretending we are testing it.

**Review by LiamMacP — APPROVED** [review]
Changes look good, tests added.

**Review by MarkWrightBjss — APPROVED** [review]

**Pull request merged**
