### PR TITLE
HOCS-2398 : update bpmn diagrams to allow escalated stages to move ca…

### PR DESCRIPTION
**Pull request by abarker66**
This update to the top level, triage escalation and draft escalation diagrams allows a user to send a case back to the Transfer stage from the Triage Escalated stage and the Draft Escalated stage.

### CODE REVIEW

**Review by LiamMacP — COMMENTED** [review]
Looks to be a good start, couple of things though: 

- This will need to go in after [HOCS-2406](https://github.com/UKHomeOffice/hocs-workflow/pull/376#pullrequestreview-581667384) as it will need to clear out the assigned user. 
- Might need to look at clearing the business unit on this change (although I will look at if there is a bigger issue with this)

**Comment by LiamMacP** [comment]
There are another set of {Triage,Draft} Escalated stages within MPAM - does this need applying to them?

**Comment by abarker66** [comment]
No because you can't change the BusArea in them - they are fixed

**Review by LiamMacP — APPROVED** [review]
Pulled branch and visually checked that code goes through the clear user. Tests look to cover this change. Approved.

**Pull request merged**
