### PR TITLE
HOCS-2819 : Acceptance deadline

### PR DESCRIPTION
**Pull request by SeanReedHomeOffice**
A Camunda timer is used for the 48 hour deadline. Specifically an interrupting timer boundary event is used. See  https://docs.camunda.io/docs/reference/bpmn-workflows/timer-events/timer-events/
The deadline is handled entirely within the Acceptance stage.
After the deadline passes the user is presented with a new screen explaining the deadline has expired.
The deadline is calculated using the Info micro-service.

### CODE REVIEW

**Comment by abarker66** [comment]
Is it necessary to inject a Clock object? the LocalDate class has built in static methods to give you now() time already.

**Comment by SeanReedHomeOffice** [comment]
> Is it necessary to inject a Clock object? the LocalDate class has built in static methods to give you now() time already.

The code is impossible to unit test without introducing the Clock. Using the clock allows you to fix what time is 'now'.

**Comment by abarker66** [comment]
Ok, I thought it was to allow testing - fair enough.

**Comment by agraham19** [comment]
You could change the Camunda expression "${bpmnService.calculateDeadline('FOI', 2)}" to pass in a "now" datetime object and get the date from that. That way when you test it, you could pass a fixed date instead.

**Review by agraham19 — APPROVED** [review]

**Pull request merged**
