### PR TITLE
HOCS-2406 unallocate user when moving back to transfer stage

### PR DESCRIPTION
**Pull request by abarker66**
Added an activity to clear the userid (unallocate) when transferring cases back to transfer stage from triage and draft stages.

### CODE REVIEW

**Comment by LiamMacP** [comment]
Worth adding some tests for this? This will also effect old cases, although not necessarily a blocker 🙂

**Comment by abarker66** [comment]
All the current bpmn processes tests pass. Don't have the time given the bug backlog.

**Comment by philbarton** [comment]
> All the current bpmn processes tests pass. Don't have the time given the bug backlog.

Our definition of done states we should have unit tests.

Without tests the next set of manual changes will likely break these changes and cause more regression bugs.

**Comment by abarker66** [comment]
'Our definition of done states we should have unit tests.' - since we have no detailed software requirements against which to test all we are doing is testing the code does what the code does and altering the tests to accommodate the functional behaviour of the code as it is. Pointless.  We should and could have a set of end to end functional tests to replace all the bpm service tests which are a set of laughable mockito vanity tests which prove nothing.

**Comment by philbarton** [comment]
> 'Our definition of done states we should have unit tests.' - since we have no detailed software requirements against which to test all we are doing is testing the code does what the code does and altering the tests to accommodate the functional behaviour of the code as it is. Pointless. We should and could have a set of end to end functional tests to replace all the bpm service tests which are a set of laughable mockito vanity tests which prove nothing.

They find merge issues in a manual merge process.

**Review by LiamMacP — APPROVED** [review]
Changes look good - tests added to aid future merge verification.

**Comment by philbarton** [comment]
This was merged without taking into account my comments. These tests aren't accurate. They miss half of the flows.

**Pull request merged**
